name: Reusable Deploy
# This workflow is reusable and can be used in other workflows
on:
  workflow_call:
    inputs:
      #Here we can specify any name
      #intut: ...
      artifact_name:
        description: The name of the deployable artifact files
        required: false # if no value then won't fail
        default: dist
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - Get Code:
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
      - name: List files
        run: ls
      - name: Output information
        run: echo "Deploying..."